### ISSUE TITLE
[Suggestion] Using `var` is an alias for `let mutable`

### ISSUE THREAD

**Issue by racklin** [ckknight/gorillascript#138] opened 2013-08-25 03:21 UTC
Using `var` is an alias for `let mutable` just like Scala Lang.
less typing less bugs ;)

**Comment by michaelficarra** [comment] 2013-08-25 03:37
I like that idea.

**Comment by ckknight** [comment] 2013-08-25 04:27
Noisy mutability is a feature, not a bug. Feel free to write your own macro, though. One nice thing about the mutable keyword is that it allows for this:

```
let [x, mutable y] = f()
```

**Comment by racklin** [comment] 2013-08-25 05:03
@ckknight Yes. I love `let` immutable and noisy `let mutable` features, I know it is not a bug.

So, i suggest to using `var` (or other keyword) is an alias or shorthand for `let mutable` .
Programmers can typing less words and prevent typo.

ex.

```
let x = 1    # x is immutable
let mutable y = 1 # y is mutable
var z = 1 # z is mutable too.
```

**Comment by vadzim** [comment] 2014-02-26 19:48
Oh no!
Noisy `let mutable` is the coolest feature.
Pls, close this issue and let `let mutable` stay noisy forever!
Typo must be prevented by code checker, not by a programmer. Programmers can also define macro in their editors. This is not a problem.

**Closed as completed** 2014-02-28 03:07 UTC
